import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import Card from "../components/Card";
import data from "../data";
import Grid from "@mui/material/Grid";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Mimic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        {/* <Grid container spacing={3}> */}
        {data?.map((data) => (
          <div>
            <Link
              href={{
                pathname: "/ticket/[id]",
                query: { id: data.id },
              }}
            >
              <Grid item xs={12} sm={6} md={4} key={data.id}>
                <Card {...data} />
              </Grid>
            </Link>
          </div>
        ))}
        {/* </Grid> */}
      </main>
    </div>
  );
}
